//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignmen1_client.OperationsReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationsReference.IOperations")]
    public interface IOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/CheckPrime", ReplyAction="http://tempuri.org/IOperations/CheckPrimeResponse")]
        bool CheckPrime(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/CheckPrime", ReplyAction="http://tempuri.org/IOperations/CheckPrimeResponse")]
        System.Threading.Tasks.Task<bool> CheckPrimeAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/DoSum", ReplyAction="http://tempuri.org/IOperations/DoSumResponse")]
        int DoSum(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/DoSum", ReplyAction="http://tempuri.org/IOperations/DoSumResponse")]
        System.Threading.Tasks.Task<int> DoSumAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/ReverseString", ReplyAction="http://tempuri.org/IOperations/ReverseStringResponse")]
        string ReverseString(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/ReverseString", ReplyAction="http://tempuri.org/IOperations/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/CreateHtml", ReplyAction="http://tempuri.org/IOperations/CreateHtmlResponse")]
        string CreateHtml(string tag, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/CreateHtml", ReplyAction="http://tempuri.org/IOperations/CreateHtmlResponse")]
        System.Threading.Tasks.Task<string> CreateHtmlAsync(string tag, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/SortNumbers", ReplyAction="http://tempuri.org/IOperations/SortNumbersResponse")]
        int[] SortNumbers(string type, int[] arrNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/SortNumbers", ReplyAction="http://tempuri.org/IOperations/SortNumbersResponse")]
        System.Threading.Tasks.Task<int[]> SortNumbersAsync(string type, int[] arrNumbers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperationsChannel : assignmen1_client.OperationsReference.IOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationsClient : System.ServiceModel.ClientBase<assignmen1_client.OperationsReference.IOperations>, assignmen1_client.OperationsReference.IOperations {
        
        public OperationsClient() {
        }
        
        public OperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckPrime(int number) {
            return base.Channel.CheckPrime(number);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPrimeAsync(int number) {
            return base.Channel.CheckPrimeAsync(number);
        }
        
        public int DoSum(int number) {
            return base.Channel.DoSum(number);
        }
        
        public System.Threading.Tasks.Task<int> DoSumAsync(int number) {
            return base.Channel.DoSumAsync(number);
        }
        
        public string ReverseString(string value) {
            return base.Channel.ReverseString(value);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string value) {
            return base.Channel.ReverseStringAsync(value);
        }
        
        public string CreateHtml(string tag, string value) {
            return base.Channel.CreateHtml(tag, value);
        }
        
        public System.Threading.Tasks.Task<string> CreateHtmlAsync(string tag, string value) {
            return base.Channel.CreateHtmlAsync(tag, value);
        }
        
        public int[] SortNumbers(string type, int[] arrNumbers) {
            return base.Channel.SortNumbers(type, arrNumbers);
        }
        
        public System.Threading.Tasks.Task<int[]> SortNumbersAsync(string type, int[] arrNumbers) {
            return base.Channel.SortNumbersAsync(type, arrNumbers);
        }
    }
}
